포스트 자동저장 실패 시 토스트 피드백
withglyph/glyph pull request #1394
Opened 2024-02-22 06:37 UTC by robin-maki

근데 아무리 임시라지만 정말 이렇게 짜도 되는 걸까요...

2024-02-22 06:37 UTC, robin-maki commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/penxle/penxle/1394?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#1394** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1394?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1384** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1384?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1376** <a href="https://app.graphite.dev/github/pr/penxle/penxle/1376?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/1394?utm_source=stack-comment).

2024-02-22 08:57 UTC, x86chi commented on apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
> +        });
P3: mixpanel.track 까지 포괄하고 있어 mixpanel tracking 이 실패해도 오류 토스트가 띄워질텐데 revisePost 으로 좁히는게 어떨까요?

2024-02-22 13:22 UTC, x86chi requested changes

2024-02-22 13:22 UTC, x86chi commented on apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
> +      let resp;
```suggestion
      let resp: Awaited<ReturnType<typeof revisePost>> | undefined;
      try {
        resp = await revisePost({
      }
      // 중략
      if (!resp) throw new Error('No response');
```

P2: `resp` 타입 명시 부탁드립니다!

2024-03-15 08:42 UTC, x86chi commented on apps/penxle.com/src/routes/editor/[permalink]/Editor.svelte
> +        toast.error('포스트를 저장하는 중에 문제가 발생했어요');
revisePost muation 오류 응답에 오류 ID가 있으면 해당 ID 를 함께 보여주면 어떨까 싶은데요, @devunt  해당 정보를 알 수 있나요?

2024-05-01 03:25 UTC, closed without merging