태그 추천 기능 추가
withglyph/glyph pull request #1591
Opened 2024-03-21 05:10 UTC by robin-maki

2024-03-21 05:10 UTC, robin-maki commented
* **#1591** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1591?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-22 05:34 UTC, devunt requested changes

2024-03-22 05:34 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/tag.ts
> +          console.log('tagUsage', tagUsage);
P1: 👀

2024-03-22 05:38 UTC, devunt approved these changes

2024-03-22 10:49 UTC, merged