비공개 스페이스로 변경 시 멤버가 아닌 사용자의 팔로우 해제
withglyph/glyph pull request #1601
Opened 2024-03-22 09:25 UTC by robin-maki

2024-03-22 09:26 UTC, robin-maki commented
* **#1601** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1601?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-29 05:21 UTC, devunt requested changes

2024-03-29 05:21 UTC, devunt commented on apps/penxle.com/src/lib/server/graphql/schemas/space.ts
> +                .select({ id: SpaceMembers.id })
P1: `SpaceMembers.id` 가 아니라 `SpaceMembers.userId` 선택해야 하는거 아닌가여?

2024-03-29 05:27 UTC, devunt approved these changes

2024-03-29 05:36 UTC, merged