GraphQL Resolver Loader 최적화
withglyph/glyph pull request #1619
Opened 2024-03-28 11:00 UTC by robin-maki

2024-03-28 11:01 UTC, robin-maki commented
* **#1619** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1619?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-30 04:01 UTC, devunt requested changes

2024-04-01 03:52 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/comment.ts
> +            }
로더 밖으로 빼면 로더 안에서 context.session 참조하는 부분이 possibly null 나서 안으로 넣었어요

2024-04-01 04:34 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +            }
역시 possibly null 이슈...

2024-04-01 05:33 UTC, devunt approved these changes

2024-04-01 05:42 UTC, merged