검색엔진 관련 리팩터링
withglyph/glyph pull request #1640
Opened 2024-04-01 07:28 UTC by robin-maki

2024-04-01 07:28 UTC, robin-maki commented
* **#1640** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1640?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-02 05:14 UTC, devunt requested changes
P2: `updatePostTags` 시에도 `indexPost` 해야 하지 않나여?!

2024-04-02 05:14 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/post.ts
> +export const calcuratePostReputation = (postId: string) =>
P1: `calculatePostReputation`

2024-04-02 05:14 UTC, devunt commented on apps/penxle.com/src/lib/server/jobs/search.ts
> +    .then(useFirstRowOrThrow());
P2: `useFirstRowOrThrow` 쓰면 post가 없으면 밑에 else로 인덱스에서 지우는게 아니라 그냥 여기서 바로 예외 던져지는거 아니에용?

2024-04-02 05:35 UTC, robin-maki commented on apps/penxle.com/src/lib/server/graphql/schemas/post.ts
> +      await enqueueJob('indexPost', input.postId);
앗 혹시 제가 빼먹은 로직이 있나요?!

2024-04-02 07:11 UTC, devunt approved these changes

2024-04-02 07:15 UTC, merged