추천 컬렉션 피드 gql
withglyph/glyph pull request #1677
Opened 2024-04-04 14:32 UTC by robin-maki

2024-04-04 14:32 UTC, robin-maki commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1677?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1677** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1677?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#1676** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1676?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1675** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1675?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-11 09:53 UTC, devunt requested changes

2024-04-11 09:53 UTC, devunt commented on apps/penxle.com/scripts/create-search-index.ts
> +        lastPostPublishedAt: { type: 'date', format: 'epoch_millis' },
P3: `epoch_millis` 여기서는 안 빼도 되는건가여

2024-04-11 09:53 UTC, devunt commented on apps/penxle.com/src/lib/server/jobs/search.ts
> +      reputation: await calculatePostReputation(collection.id),
P1: `calculateCollectionReputation` 이어야 하는거겠져?

2024-04-11 09:53 UTC, devunt commented on apps/penxle.com/src/lib/server/utils/post.ts
> +export const calcurateCollectionReputation = async (collectionId: string) =>
P2: `calculate`

2024-04-11 12:08 UTC, devunt approved these changes

2024-04-11 12:13 UTC, merged