게시 옵션 모달 내 중복 스타일 병합해서 재사용하기
withglyph/glyph pull request #1732
Opened 2024-04-11 15:23 UTC by mu-hun

2024-04-11 15:24 UTC, mu-hun commented
* **#1734** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1734?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1733** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1733?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#1732** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1732?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mu-hun and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-11 16:32 UTC, devunt requested changes

2024-04-11 16:32 UTC, devunt commented on apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
> +  } as const;
P3: `css.raw({...})` 함수 이용을 추천드립니다.

2024-04-11 16:32 UTC, devunt commented on apps/penxle.com/src/routes/editor/[permalink]/PublishMenu.svelte
> +  const labelWidthDescriptionStyle = css({
P2: `labelWithDescriptionStyle` 일까요?

2024-04-12 05:48 UTC, devunt approved these changes

2024-04-12 06:00 UTC, merged