본인인증 유효기간 도입
withglyph/glyph pull request #1942
Opened 2024-04-23 07:42 UTC by robin-maki

마이그레이션 적용 후 스크립트 돌려서 expiredAt 보정해야할듯

2024-04-23 07:43 UTC, robin-maki commented
* **#1942** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/1942?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-04-23 08:35 UTC, devunt requested changes

2024-04-23 08:35 UTC, devunt commented on apps/website/src/lib/server/database/schemas/tables.ts
> +    .default(sql`now() + interval '1 year'`),
P2: 이름 `expires_at` 이 맞는 듯 해요 (보통의 경우 아직 만료된게 아니니)
P1: 개인적으로 sql에 비즈니스 로직 넣는걸 별로 안 좋아해서,,,, 요 값은 서버 로직에서 넣어주는게 어떨까용

2024-04-23 08:39 UTC, robin-maki commented on apps/website/src/lib/server/database/schemas/tables.ts
> +    .default(sql`now() + interval '1 year'`),
방금 생각해봤는데 얘 nullable이여도 될 거 같죠?? 뭐 외국인 본인인증 같은건 1년으로 제한하라는 법은 없으니까... 글구 nullable이면 마이그레이션 문제도 해결이구...

2024-04-23 08:39 UTC, devunt commented on apps/website/src/lib/server/database/schemas/tables.ts
> +    .default(sql`now() + interval '1 year'`),
넹 그래도 될 것 같습니다

2024-04-23 08:41 UTC, devunt approved these changes

2024-04-25 06:21 UTC, robin-maki commented
마이그레이션 만들고 테섭 DB에 적용했어요!!

2024-04-25 06:26 UTC, merged

2024-04-25 06:28 UTC, robin-maki commented
마이그레이션 그냥 
```sql
UPDATE user_personal_identities set expires_at=created_at+interval '1 year';
``` 
하면 되네요... Prisma에 절여졌던 그동안의 삶을 반성