리딤코드 gql
withglyph/glyph pull request #2159
Opened 2024-05-17 10:36 UTC by robin-maki

2024-05-17 10:36 UTC, robin-maki commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/withglyph/glyph/2159?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2159** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/2159?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#2154** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/2154?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-13 07:03 UTC, devunt requested changes

2024-06-13 07:06 UTC, devunt requested changes

2024-06-13 07:06 UTC, devunt commented on apps/website/src/lib/server/graphql/schemas/redeem.ts
> +      }
P1: 스페이스 멤버인지도 확인 필요 (일단 지금 구현체에서는 스페이스 멤버는 같은 스페이스에 있는 유료 글 구매 못함)

2024-06-13 07:47 UTC, robin-maki commented on apps/website/src/lib/server/graphql/schemas/redeem.ts
> +const generateRedeemCode = customAlphabet('HMN34P67R9TWCXYF', 20);
https://stackoverflow.com/a/27459196 요거를 참고했어요

2024-06-13 08:01 UTC, robin-maki commented on apps/website/src/lib/server/graphql/schemas/redeem.ts
> +    type: Post,
`PostPurchase`가 없다는 큰 문제가 있네요... 근데 그래도 확실히 이걸 구현하는 편이 더 나은 거 같아 보여요

2024-06-17 03:47 UTC, devunt approved these changes

2024-06-17 03:59 UTC, merged