알림 전체 읽기 gql
withglyph/glyph pull request #2250
Opened 2024-05-30 10:32 UTC by robin-maki

프론트 코드도 수정했어요

2024-05-30 10:32 UTC, robin-maki commented
* **#2250** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/2250?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-30 11:02 UTC, Seohyun-Roh requested changes
사실 `readAllNotifications`가 두 곳에 있어요

2024-05-30 11:03 UTC, devunt approved these changes

2024-05-31 03:00 UTC, Seohyun-Roh approved these changes

2024-05-31 07:33 UTC, merged