24시간 이상 된 스냅샷 삭제 스크립트
withglyph/glyph pull request #2827
Opened 2024-10-22 10:37 UTC by robin-maki

체크 받고 실행 예정

2024-10-22 10:37 UTC, robin-maki commented
* **#2827** <a href="https://app.graphite.dev/github/pr/withglyph/glyph/2827?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @robin-maki and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-23 03:50 UTC, devunt requested changes

2024-10-23 03:50 UTC, devunt commented on apps/website/scripts/delete-old-snapshot.ts
> +  const posts = await database.select({ id: Posts.id }).from(Posts).where(gt(Posts.id, lastId)).limit(100);
P1: 여기 id로 order by asc 들어가야 하지 않나용

2024-10-23 03:54 UTC, devunt approved these changes

2024-10-23 04:00 UTC, devunt commented
### Merge activity

* **Oct 23, 12:00 AM EDT**: The merge label ':rocket:' was detected. This PR will be added to the [Graphite merge queue](https://app.graphite.dev/merges?org=withglyph&repo=glyph) once it meets the requirements.

2024-10-23 04:07 UTC, merged